#!/bin/bash
source scripts-config
if [ $# -eq 0 ]
then
    if [-d .git ]
    then 
        REPO=${PWD##*/}
        ssh $SERVER_ADDRESS "
            cd $DEFAULT_LOCATION;
            mv $DEFAULT_LOCATION/$REPO $ARCHIVE_LOCATION;   
        "
        cd ..
        rm -rf $REPO
    else 
        echo "Please call 'archive' in or on a git repo"
    fi
    # This is rough but since its passwordless idc. do it a million times for all I care
else
    for REPO in $@ 
    do 
        ssh $SERVER_ADDRESS "
            cd $DEFAULT_LOCATION;
            mv $DEFAULT_LOCATION/$REPO $ARCHIVE_LOCATION;    
        "
        rm -rf $REPO
        # This is rough but since its passwordless idc. do it a million times for all I care
    done 
fi