#!/bin/bash
source scripts-config
for NEW_FOLDER in $@
do
    ssh $SERVER_ADDRESS "
    cd $DEFAULT_LOCATION; 
    mkdir $NEW_FOLDER; 
    cd $NEW_FOLDER; 
    git init --bare; 
    exit;"
done
for NEW_FOLDER in $@
do
    git clone $SERVER_ADDRESS:$DEFAULT_LOCATION/$NEW_FOLDER
done 
echo Added reops: $@ and saved copies to $(pwd)
