#!/bin/bash
source scripts-config

for REPO in $@ 
do 
    ssh $SERVER_ADDRESS "
        cd $ARCHIVE_LOCATION;
        mv $ARCHIVE_LOCATION/$REPO $DEFAULT_LOCATION;    
    "
    get $REPO
    # This is rough but since its passwordless idc. do it a million times for all I care
done 